apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\openshift-origin-client-tools-v3.11.0-0cbc58b-windows\kompose-windows-amd64.exe
      convert -f .\docker-compose.yml --provider=openshift -o ./openshift_build
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: customer-management-backend
  name: customer-management-backend
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 8100
  selector:
    io.kompose.service: customer-management-backend
status:
  loadBalancer: {}
