apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: customer-self-service-backend
  name: customer-self-service-backend
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.appuio.ch/appuio-demo9506/customer-self-service-backend
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
