apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\openshift-origin-client-tools-v3.11.0-0cbc58b-windows\kompose-windows-amd64.exe
      convert -f .\docker-compose.yml --provider=openshift -o ./openshift_build
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: customer-core
  name: customer-core
spec:
  ports:
  - name: "8110"
    port: 8110
    targetPort: 8110
  selector:
    io.kompose.service: customer-core
status:
  loadBalancer: {}
