apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\openshift-origin-client-tools-v3.11.0-0cbc58b-windows\kompose-windows-amd64.exe
      convert -f .\docker-compose.yml --provider=openshift -o ./openshift_build
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: policy-management-backend
  name: policy-management-backend
spec:
  ports:
  - name: "8090"
    port: 8090
    targetPort: 8090
  - name: "61613"
    port: 61613
    targetPort: 61613
  - name: "61616"
    port: 61616
    targetPort: 61616
  selector:
    io.kompose.service: policy-management-backend
status:
  loadBalancer: {}
