apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: policy-management-frontend
  name: policy-management-frontend
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.appuio.ch/appuio-demo9506/policy-management-frontend
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
