apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: spring-boot-admin
  name: spring-boot-admin
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.appuio.ch/appuio-demo9506/spring-boot-admin
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
