apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: C:\openshift-origin-client-tools-v3.11.0-0cbc58b-windows\kompose-windows-amd64.exe
      convert -f .\docker-compose.yml --provider=openshift -o ./openshift_build
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: spring-boot-admin
  name: spring-boot-admin
spec:
  replicas: 1
  selector:
    io.kompose.service: spring-boot-admin
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: spring-boot-admin
    spec:
      containers:
      - image: ' '
        name: spring-boot-admin
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - spring-boot-admin
      from:
        kind: ImageStreamTag
        name: spring-boot-admin:latest
    type: ImageChange
status: {}
